### ISSUE TITLE
Error after 64512 connections in MQTT Load Simulator v1.3.1

### ISSUE THREAD

**Issue by abbashussainz** [halfgaar/MqttLoadSimulator#2]
I am using the MQTT Load Simulator version 1.3.1 to simulate MQTT connections, but I am encountering an error after reaching 64512 connections. I would like to report this issue and seek assistance in resolving it.

``` 
ubuntu@ip-10-217-97-18:~/appimage$ ./MqttLoadSimulator.appimage --hostname=54.216.77.53 --amount-active 100000 --msg-per-burst 0 --delay 30
Version: 1.3.1. Clients: 100001 on 96 threads. Sent: 0 (0/s). Recv: 0 (0/s). Recv-Sent: 0. Connects: 63128 (0/s). Disconnects: 0 (0/s). Errors: 14983 (2785/s). 
Thread loop drift: Avg: 13.05 ms, max: 24 ms (OK) 
```

**Comment by halfgaar** [comment]
Hi there,

To create more than about 32000 clients, you need to use multiple IP addresses to work around the TCP ephemeral port limit.. The easiest is to give the server multiple addresses, and then use the `--hostname-list` option, like:

```
./MqttLoadSimulator.AppImage --hostname-list 10.0.0.1,10.0.0.2,10.0.0.3
```
