### ISSUE TITLE
How to calculate average/ min.

### ISSUE THREAD

**Issue by Nigelwz** [halfgaar/MqttLoadSimulator#3]
I using the tool to test our broker.
Can I know how to calculate average/max time.

average response time or max response time?

**Comment by halfgaar** [comment]
Some kind of latency check would be a good addition, but as of yet, it can't.

It wouldn't be super hard to do: I can add a monotonic/steady timestamp to the payload and compare it on receive.

**Comment by Nigelwz** [comment]
Ok, I got it, I can help to test. thanks.
Can we add qmqtt be a submodule? I think if other people need to use it, it's conveninet to build it by user.

**Comment by halfgaar** [comment]
I released version 1.4.0. Binaries are [here](https://www.flashmq.org/download/mqtt-load-simulator/).

I'll consider it done and close the ticket.

> Can we add qmqtt be a submodule? I think if other people need to use it, it's conveninet to build it by user.

A git submodule? I'm unsure how easy it would be. Currently, it builds as a module that needs to be installed into the Qt directory.

Also, I would like to port it to the official [QtQmqtt](https://github.com/qt/qtmqtt). Then I can also include MQTTv5 and websocket testing.
